# Generated by Django 3.2.5 on 2023-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField(verbose_name='date_published')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d')),
                ('category', models.ManyToManyField(to='blog.Category')),
            ],
        ),
    ]
